
/*<auto-generated>
***End of Global definition area***
Changes to this comment may cause incorrect behavior during document based import.
</auto-generated>*/
export function HighlightButton(ButtonName, ButtonsScreenPath) {
  // Highlights the active menu button and set all other buttons to default colors.
 
if (!ButtonsScreenPath)
{
ButtonsScreenPath = "";
}
  const number = ButtonName.replace(/^\D+/g, '');
  const BtnName = ButtonName.slice(0, ButtonName.lastIndexOf(number));
  
  let highlightColor = HMIRuntime.Math.RGB(0,161,209,255);
  let defaultColor = HMIRuntime.Math.RGB(181,190,197,255);

  if (BtnName === "txtMainNav") {
    defaultColor = HMIRuntime.Math.RGB(38,39,41,255);
  }

  for(let i = 1; i < 20; i++) {
    const currentButton = Screen.FindItem(ButtonsScreenPath + BtnName + i);
    if (!currentButton) {
      break;
    }
    if(ButtonName === currentButton.Name) {
      currentButton.BackColor = highlightColor;
    } else {
      currentButton.BackColor = defaultColor;
    }
  } 
}
export function ShowMainNavigation() {
  // Set the main navigation visible
  Screen.FindItem("~/swMainNavigation").Visible =
    Screen.FindItem("~/btnHideMainNavigation").Visible = true;
}
export function HideSubNavigation() {
  // Set the sub navigation invisible
  Screen.FindItem("~/swSubNavigation").Visible = false;
}
export function HideMainNavigation() {
  // Set the main navigation invisible
  Screen.FindItem("~/swMainNavigation").Visible =
    Screen.FindItem("~/btnHideMainNavigation").Visible = false;
}
export function ShowSubNavigation(ButtonNumber) {
// Set the sub navigation visible and highlight button by number (if no number given, first button will be highlighted)
  const subNavigation = Screen.FindItem("~/swSubNavigation");
  subNavigation.Visible = true;
  if (!ButtonNumber) {
    ButtonNumber = 1;
  }
  // set an inner property of the screen, so the update of the button to highlight will be triggered
  subNavigation.CurrentScreen.AlternateBackColor = ButtonNumber;
  // set an outer property of the navigation so the correct button gets also highlighted,
  // even if the navigation will be changed by a "ScreenChange", because the inner property change will be lost then.
  subNavigation.HorizontalScrollBarPosition = ButtonNumber;
}
